language: node_js
services:
  - mongodb
before_install: npm install -g grunt-cli
install:
  - npm install
  - ruby -v
  - gem install sass
script:
  - cp config.js.example config.js
  - grunt test
  - grunt build
